"""Контракт хранилища.

Всё остальное приложение работает с этим протоколом и ничего не знает про
SQL. Смысл ровно в одном: когда SQLite перестанет хватать (несколько процессов
пишут одновременно), Postgres добавляется новой реализацией этого же интерфейса,
без единой правки в опросе, вендорах и вебе.
"""

from __future__ import annotations

from typing import Protocol

from device_monitor.domain.models import Category, Device, Site


class Storage(Protocol):
    # -- точки
    def sites(self) -> list[Site]: ...
    def site(self, name: str) -> Site | None: ...
    def add_site(self, site: Site) -> Site: ...
    def update_site(self, old_name: str, site: Site) -> Site: ...
    def delete_site(self, name: str) -> None: ...

    # -- категории
    def categories(self) -> list[Category]: ...
    def add_category(self, site: str, name: str, note: str) -> Category: ...
    def update_category(self, site: str, old: str, name: str, note: str) -> Category: ...
    def delete_category(self, site: str, name: str) -> None: ...

    # -- устройства
    def devices(self) -> list[Device]: ...
    def device(self, device_id: str) -> Device | None: ...
    def add_device(self, device: Device) -> Device: ...
    def update_device(self, device: Device) -> Device: ...
    def delete_device(self, device_id: str) -> bool: ...

    # -- история состояний
    def record_status(self, device_id: str, status: str, at: str) -> None: ...
    def last_status(self, device_id: str) -> str | None: ...
    def history(self, device_id: str, limit: int) -> list[dict]: ...
    def uptime(self, device_id: str, days: int) -> dict: ...
    def prune_history(self, days: int) -> int: ...
